spring.application.name=course-recommender

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Main}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# ── JPA formatting ───────────────────────────────────
spring.jpa.properties.hibernate.format_sql=true


# ── Thymeleaf ────────────────────────────────────────
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.jpa.open-in-view=true
